### PR TITLE
added public hash to tokens

### PR DESCRIPTION
**Pull request by mstein-ck**

### CODE REVIEW

**Comment by mstein-ck** [comment]
@dlehren can you review

**Comment by dlehren** [comment]
Looks good, we still need to figure out how to fix saved payment methods that did not have a public hash orginally.

**Comment by mstein-ck** [comment]
> 
> 
> Looks good, we still need to figure out how to fix saved payment methods that did not have a public hash originally.

Won't that have to be done manually

**Comment by dlehren** [comment]
> > Looks good, we still need to figure out how to fix saved payment methods that did not have a public hash originally.
> 
> Won't that have to be done manually

It might be possible to hide all cards that don't have a hash or have a script that runs when the plugin is updated to add hashes to the old saved methods.

**Pull request merged**
